// <auto-generated />
using System;
using Fenio1.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fenio1.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414082525_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Fenio1.Core.Entities.Circuit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<int>("LapCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LengthKm")
                        .HasColumnType("decimal(6,3)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Circuits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Bahrain",
                            CountryCode = "BH",
                            LapCount = 57,
                            LengthKm = 5.412m,
                            Location = "Sakhir",
                            Name = "Bahrain International Circuit"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Saudi Arabia",
                            CountryCode = "SA",
                            LapCount = 50,
                            LengthKm = 6.174m,
                            Location = "Jeddah",
                            Name = "Jeddah Corniche Circuit"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Australia",
                            CountryCode = "AU",
                            LapCount = 58,
                            LengthKm = 5.278m,
                            Location = "Melbourne",
                            Name = "Albert Park Circuit"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Japan",
                            CountryCode = "JP",
                            LapCount = 53,
                            LengthKm = 5.807m,
                            Location = "Suzuka",
                            Name = "Suzuka International Racing Course"
                        },
                        new
                        {
                            Id = 5,
                            Country = "China",
                            CountryCode = "CN",
                            LapCount = 56,
                            LengthKm = 5.451m,
                            Location = "Shanghai",
                            Name = "Shanghai International Circuit"
                        },
                        new
                        {
                            Id = 6,
                            Country = "USA",
                            CountryCode = "US",
                            LapCount = 57,
                            LengthKm = 5.412m,
                            Location = "Miami",
                            Name = "Miami International Autodrome"
                        },
                        new
                        {
                            Id = 7,
                            Country = "Italy",
                            CountryCode = "IT",
                            LapCount = 63,
                            LengthKm = 4.909m,
                            Location = "Imola",
                            Name = "Autodromo Enzo e Dino Ferrari"
                        },
                        new
                        {
                            Id = 8,
                            Country = "Monaco",
                            CountryCode = "MC",
                            LapCount = 78,
                            LengthKm = 3.337m,
                            Location = "Monte Carlo",
                            Name = "Circuit de Monaco"
                        },
                        new
                        {
                            Id = 9,
                            Country = "Spain",
                            CountryCode = "ES",
                            LapCount = 66,
                            LengthKm = 4.657m,
                            Location = "Barcelona",
                            Name = "Circuit de Barcelona-Catalunya"
                        },
                        new
                        {
                            Id = 10,
                            Country = "Canada",
                            CountryCode = "CA",
                            LapCount = 70,
                            LengthKm = 4.361m,
                            Location = "Montreal",
                            Name = "Circuit Gilles Villeneuve"
                        });
                });

            modelBuilder.Entity("Fenio1.Core.Entities.ConstructorStanding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("SeasonId", "TeamId")
                        .IsUnique();

                    b.ToTable("ConstructorStandings");
                });

            modelBuilder.Entity("Fenio1.Core.Entities.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<int>("DriverNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "VER",
                            DateOfBirth = new DateTime(1997, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriverNumber = 1,
                            FirstName = "Max",
                            IsActive = true,
                            LastName = "Verstappen",
                            Nationality = "Dutch",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "PER",
                            DateOfBirth = new DateTime(1990, 1, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriverNumber = 11,
                            FirstName = "Sergio",
                            IsActive = true,
                            LastName = "Perez",
                            Nationality = "Mexican",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "LEC",
                            DateOfBirth = new DateTime(1997, 10, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriverNumber = 16,
                            FirstName = "Charles",
                            IsActive = true,
                            LastName = "Leclerc",
                            Nationality = "Monégasque",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 4,
                            Code = "HAM",
                            DateOfBirth = new DateTime(1985, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriverNumber = 44,
                            FirstName = "Lewis",
                            IsActive = true,
                            LastName = "Hamilton",
                            Nationality = "British",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 5,
                            Code = "RUS",
                            DateOfBirth = new DateTime(1998, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriverNumber = 63,
                            FirstName = "George",
                            IsActive = true,
                            LastName = "Russell",
                            Nationality = "British",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 6,
                            Code = "ANT",
                            DateOfBirth = new DateTime(2006, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriverNumber = 12,
                            FirstName = "Kimi",
                            IsActive = true,
                            LastName = "Antonelli",
                            Nationality = "Italian",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 7,
                            Code = "NOR",
                            DateOfBirth = new DateTime(1999, 11, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriverNumber = 4,
                            FirstName = "Lando",
                            IsActive = true,
                            LastName = "Norris",
                            Nationality = "British",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 8,
                            Code = "PIA",
                            DateOfBirth = new DateTime(2001, 4, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriverNumber = 81,
                            FirstName = "Oscar",
                            IsActive = true,
                            LastName = "Piastri",
                            Nationality = "Australian",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 9,
                            Code = "ALO",
                            DateOfBirth = new DateTime(1981, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriverNumber = 14,
                            FirstName = "Fernando",
                            IsActive = true,
                            LastName = "Alonso",
                            Nationality = "Spanish",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 10,
                            Code = "STR",
                            DateOfBirth = new DateTime(1998, 10, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriverNumber = 18,
                            FirstName = "Lance",
                            IsActive = true,
                            LastName = "Stroll",
                            Nationality = "Canadian",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 11,
                            Code = "GAS",
                            DateOfBirth = new DateTime(1996, 2, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriverNumber = 10,
                            FirstName = "Pierre",
                            IsActive = true,
                            LastName = "Gasly",
                            Nationality = "French",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 12,
                            Code = "DOO",
                            DateOfBirth = new DateTime(2003, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriverNumber = 7,
                            FirstName = "Jack",
                            IsActive = true,
                            LastName = "Doohan",
                            Nationality = "Australian",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 13,
                            Code = "ALB",
                            DateOfBirth = new DateTime(1996, 3, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriverNumber = 23,
                            FirstName = "Alexander",
                            IsActive = true,
                            LastName = "Albon",
                            Nationality = "Thai",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 14,
                            Code = "SAI",
                            DateOfBirth = new DateTime(1994, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriverNumber = 55,
                            FirstName = "Carlos",
                            IsActive = true,
                            LastName = "Sainz",
                            Nationality = "Spanish",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 15,
                            Code = "TSU",
                            DateOfBirth = new DateTime(2000, 5, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriverNumber = 22,
                            FirstName = "Yuki",
                            IsActive = true,
                            LastName = "Tsunoda",
                            Nationality = "Japanese",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 16,
                            Code = "LAW",
                            DateOfBirth = new DateTime(2002, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriverNumber = 30,
                            FirstName = "Liam",
                            IsActive = true,
                            LastName = "Lawson",
                            Nationality = "New Zealander",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 17,
                            Code = "HUL",
                            DateOfBirth = new DateTime(1987, 8, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriverNumber = 27,
                            FirstName = "Nico",
                            IsActive = true,
                            LastName = "Hülkenberg",
                            Nationality = "German",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 18,
                            Code = "BOR",
                            DateOfBirth = new DateTime(2004, 10, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriverNumber = 5,
                            FirstName = "Gabriel",
                            IsActive = true,
                            LastName = "Bortoleto",
                            Nationality = "Brazilian",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 19,
                            Code = "OCO",
                            DateOfBirth = new DateTime(1996, 9, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriverNumber = 31,
                            FirstName = "Esteban",
                            IsActive = true,
                            LastName = "Ocon",
                            Nationality = "French",
                            TeamId = 10
                        },
                        new
                        {
                            Id = 20,
                            Code = "BEA",
                            DateOfBirth = new DateTime(2005, 5, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriverNumber = 87,
                            FirstName = "Oliver",
                            IsActive = true,
                            LastName = "Bearman",
                            Nationality = "British",
                            TeamId = 10
                        });
                });

            modelBuilder.Entity("Fenio1.Core.Entities.DriverStanding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DriverId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("Podiums")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("SeasonId", "DriverId")
                        .IsUnique();

                    b.ToTable("DriverStandings");
                });

            modelBuilder.Entity("Fenio1.Core.Entities.Prediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PredictedDnfDriverId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PredictedDriverOfTheDayId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PredictedFastestLapDriverId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PredictedFastestPitStopDriverId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PredictedSafetyCarCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PredictedScoredPointsDriverId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RaceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalPointsForRace")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PredictedDnfDriverId");

                    b.HasIndex("PredictedDriverOfTheDayId");

                    b.HasIndex("PredictedFastestLapDriverId");

                    b.HasIndex("PredictedFastestPitStopDriverId");

                    b.HasIndex("PredictedScoredPointsDriverId");

                    b.HasIndex("RaceId");

                    b.HasIndex("UserId", "RaceId")
                        .IsUnique();

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("Fenio1.Core.Entities.PredictionLeaderboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RacesParticipated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("UserId", "SeasonId")
                        .IsUnique();

                    b.ToTable("PredictionLeaderboards");
                });

            modelBuilder.Entity("Fenio1.Core.Entities.PredictionQualifyingPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DriverId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PredictionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("PredictionId", "Position")
                        .IsUnique();

                    b.ToTable("PredictionQualifyingPositions");
                });

            modelBuilder.Entity("Fenio1.Core.Entities.PredictionRacePosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DriverId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PredictionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("PredictionId", "Position")
                        .IsUnique();

                    b.ToTable("PredictionRacePositions");
                });

            modelBuilder.Entity("Fenio1.Core.Entities.PredictionSprintPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DriverId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PredictionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("PredictionId", "Position")
                        .IsUnique();

                    b.ToTable("PredictionSprintPositions");
                });

            modelBuilder.Entity("Fenio1.Core.Entities.QualifyingResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DriverId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Q1Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Q2Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Q3Time")
                        .HasColumnType("TEXT");

                    b.Property<int>("RaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("RaceId", "DriverId")
                        .IsUnique();

                    b.HasIndex("RaceId", "Position")
                        .IsUnique();

                    b.ToTable("QualifyingResults");
                });

            modelBuilder.Entity("Fenio1.Core.Entities.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CircuitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalApiId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasSprint")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("QualifyingDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RaceDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SprintDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CircuitId");

                    b.HasIndex("SeasonId", "RoundNumber")
                        .IsUnique();

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CircuitId = 1,
                            HasSprint = false,
                            Name = "Bahrain Grand Prix",
                            QualifyingDate = new DateTime(2025, 3, 1, 15, 0, 0, 0, DateTimeKind.Utc),
                            RaceDate = new DateTime(2025, 3, 2, 15, 0, 0, 0, DateTimeKind.Utc),
                            RoundNumber = 1,
                            SeasonId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            CircuitId = 2,
                            HasSprint = false,
                            Name = "Saudi Arabian Grand Prix",
                            QualifyingDate = new DateTime(2025, 3, 8, 20, 0, 0, 0, DateTimeKind.Utc),
                            RaceDate = new DateTime(2025, 3, 9, 20, 0, 0, 0, DateTimeKind.Utc),
                            RoundNumber = 2,
                            SeasonId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            CircuitId = 3,
                            HasSprint = false,
                            Name = "Australian Grand Prix",
                            QualifyingDate = new DateTime(2025, 3, 15, 6, 0, 0, 0, DateTimeKind.Utc),
                            RaceDate = new DateTime(2025, 3, 16, 6, 0, 0, 0, DateTimeKind.Utc),
                            RoundNumber = 3,
                            SeasonId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            CircuitId = 5,
                            HasSprint = true,
                            Name = "Chinese Grand Prix",
                            QualifyingDate = new DateTime(2025, 3, 22, 7, 0, 0, 0, DateTimeKind.Utc),
                            RaceDate = new DateTime(2025, 3, 23, 7, 0, 0, 0, DateTimeKind.Utc),
                            RoundNumber = 4,
                            SeasonId = 1,
                            SprintDate = new DateTime(2025, 3, 22, 11, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            CircuitId = 6,
                            HasSprint = true,
                            Name = "Miami Grand Prix",
                            QualifyingDate = new DateTime(2025, 5, 3, 20, 0, 0, 0, DateTimeKind.Utc),
                            RaceDate = new DateTime(2025, 5, 4, 20, 0, 0, 0, DateTimeKind.Utc),
                            RoundNumber = 5,
                            SeasonId = 1,
                            SprintDate = new DateTime(2025, 5, 3, 15, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0
                        });
                });

            modelBuilder.Entity("Fenio1.Core.Entities.RaceExtra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DnfDriverId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DriverOfTheDayId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FastestLapDriverId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FastestPitStopDriverId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SafetyCarCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ScoredPointsDriverId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DnfDriverId");

                    b.HasIndex("DriverOfTheDayId");

                    b.HasIndex("FastestLapDriverId");

                    b.HasIndex("FastestPitStopDriverId");

                    b.HasIndex("RaceId")
                        .IsUnique();

                    b.HasIndex("ScoredPointsDriverId");

                    b.ToTable("RaceExtras");
                });

            modelBuilder.Entity("Fenio1.Core.Entities.RaceResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DidNotFinish")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DnfReason")
                        .HasColumnType("TEXT");

                    b.Property<int>("DriverId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FastestLap")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FastestPitStop")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GridPosition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LapTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PitStopTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PointsScored")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("RaceId", "DriverId")
                        .IsUnique();

                    b.HasIndex("RaceId", "Position")
                        .IsUnique();

                    b.ToTable("RaceResults");
                });

            modelBuilder.Entity("Fenio1.Core.Entities.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("Seasons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Formula 1 2025 Season",
                            Year = 2025
                        });
                });

            modelBuilder.Entity("Fenio1.Core.Entities.SprintResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DidNotFinish")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DriverId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PointsScored")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("RaceId", "DriverId")
                        .IsUnique();

                    b.HasIndex("RaceId", "Position")
                        .IsUnique();

                    b.ToTable("SprintResults");
                });

            modelBuilder.Entity("Fenio1.Core.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Red Bull Racing",
                            Nationality = "Austrian",
                            PrimaryColor = "#3671C6",
                            ShortName = "Red Bull"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Scuderia Ferrari",
                            Nationality = "Italian",
                            PrimaryColor = "#E8002D",
                            ShortName = "Ferrari"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Mercedes-AMG Petronas",
                            Nationality = "German",
                            PrimaryColor = "#27F4D2",
                            ShortName = "Mercedes"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "McLaren F1 Team",
                            Nationality = "British",
                            PrimaryColor = "#FF8000",
                            ShortName = "McLaren"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Aston Martin Aramco",
                            Nationality = "British",
                            PrimaryColor = "#229971",
                            ShortName = "Aston Martin"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "BWT Alpine F1 Team",
                            Nationality = "French",
                            PrimaryColor = "#0093CC",
                            ShortName = "Alpine"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Williams Racing",
                            Nationality = "British",
                            PrimaryColor = "#64C4FF",
                            ShortName = "Williams"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "Visa Cash App RB",
                            Nationality = "Italian",
                            PrimaryColor = "#6692FF",
                            ShortName = "RB"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Name = "Stake F1 Team Kick Sauber",
                            Nationality = "Swiss",
                            PrimaryColor = "#52E252",
                            ShortName = "Sauber"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Name = "MoneyGram Haas F1 Team",
                            Nationality = "American",
                            PrimaryColor = "#B6BABD",
                            ShortName = "Haas"
                        });
                });

            modelBuilder.Entity("Fenio1.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@fenio1.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$JahuhaS3JzM37Jl0lAmTqe6mzZW.w7M8J9lBZVsvSHAUiqAmvYk9O",
                            Role = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user1@fenio1.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$ECvhVBe0IePbMVg3UAaAkuZC2g3BIjw1QcYRW4P1AwLygItqr7sw.",
                            Role = 0,
                            Username = "user1"
                        });
                });

            modelBuilder.Entity("Fenio1.Core.Entities.ConstructorStanding", b =>
                {
                    b.HasOne("Fenio1.Core.Entities.Season", "Season")
                        .WithMany("ConstructorStandings")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fenio1.Core.Entities.Team", "Team")
                        .WithMany("ConstructorStandings")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Fenio1.Core.Entities.Driver", b =>
                {
                    b.HasOne("Fenio1.Core.Entities.Team", "Team")
                        .WithMany("Drivers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Fenio1.Core.Entities.DriverStanding", b =>
                {
                    b.HasOne("Fenio1.Core.Entities.Driver", "Driver")
                        .WithMany("DriverStandings")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fenio1.Core.Entities.Season", "Season")
                        .WithMany("DriverStandings")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Fenio1.Core.Entities.Prediction", b =>
                {
                    b.HasOne("Fenio1.Core.Entities.Driver", "PredictedDnfDriver")
                        .WithMany()
                        .HasForeignKey("PredictedDnfDriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fenio1.Core.Entities.Driver", "PredictedDriverOfTheDay")
                        .WithMany()
                        .HasForeignKey("PredictedDriverOfTheDayId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fenio1.Core.Entities.Driver", "PredictedFastestLapDriver")
                        .WithMany()
                        .HasForeignKey("PredictedFastestLapDriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fenio1.Core.Entities.Driver", "PredictedFastestPitStopDriver")
                        .WithMany()
                        .HasForeignKey("PredictedFastestPitStopDriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fenio1.Core.Entities.Driver", "PredictedScoredPointsDriver")
                        .WithMany()
                        .HasForeignKey("PredictedScoredPointsDriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fenio1.Core.Entities.Race", "Race")
                        .WithMany("Predictions")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fenio1.Core.Entities.User", "User")
                        .WithMany("Predictions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PredictedDnfDriver");

                    b.Navigation("PredictedDriverOfTheDay");

                    b.Navigation("PredictedFastestLapDriver");

                    b.Navigation("PredictedFastestPitStopDriver");

                    b.Navigation("PredictedScoredPointsDriver");

                    b.Navigation("Race");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fenio1.Core.Entities.PredictionLeaderboard", b =>
                {
                    b.HasOne("Fenio1.Core.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fenio1.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fenio1.Core.Entities.PredictionQualifyingPosition", b =>
                {
                    b.HasOne("Fenio1.Core.Entities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fenio1.Core.Entities.Prediction", "Prediction")
                        .WithMany("QualifyingPositions")
                        .HasForeignKey("PredictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Prediction");
                });

            modelBuilder.Entity("Fenio1.Core.Entities.PredictionRacePosition", b =>
                {
                    b.HasOne("Fenio1.Core.Entities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fenio1.Core.Entities.Prediction", "Prediction")
                        .WithMany("RacePositions")
                        .HasForeignKey("PredictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Prediction");
                });

            modelBuilder.Entity("Fenio1.Core.Entities.PredictionSprintPosition", b =>
                {
                    b.HasOne("Fenio1.Core.Entities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fenio1.Core.Entities.Prediction", "Prediction")
                        .WithMany("SprintPositions")
                        .HasForeignKey("PredictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Prediction");
                });

            modelBuilder.Entity("Fenio1.Core.Entities.QualifyingResult", b =>
                {
                    b.HasOne("Fenio1.Core.Entities.Driver", "Driver")
                        .WithMany("QualifyingResults")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fenio1.Core.Entities.Race", "Race")
                        .WithMany("QualifyingResults")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Fenio1.Core.Entities.Race", b =>
                {
                    b.HasOne("Fenio1.Core.Entities.Circuit", "Circuit")
                        .WithMany("Races")
                        .HasForeignKey("CircuitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fenio1.Core.Entities.Season", "Season")
                        .WithMany("Races")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Circuit");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Fenio1.Core.Entities.RaceExtra", b =>
                {
                    b.HasOne("Fenio1.Core.Entities.Driver", "DnfDriver")
                        .WithMany()
                        .HasForeignKey("DnfDriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fenio1.Core.Entities.Driver", "DriverOfTheDay")
                        .WithMany()
                        .HasForeignKey("DriverOfTheDayId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fenio1.Core.Entities.Driver", "FastestLapDriver")
                        .WithMany()
                        .HasForeignKey("FastestLapDriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fenio1.Core.Entities.Driver", "FastestPitStopDriver")
                        .WithMany()
                        .HasForeignKey("FastestPitStopDriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fenio1.Core.Entities.Race", "Race")
                        .WithMany("RaceExtras")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fenio1.Core.Entities.Driver", "ScoredPointsDriver")
                        .WithMany()
                        .HasForeignKey("ScoredPointsDriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DnfDriver");

                    b.Navigation("DriverOfTheDay");

                    b.Navigation("FastestLapDriver");

                    b.Navigation("FastestPitStopDriver");

                    b.Navigation("Race");

                    b.Navigation("ScoredPointsDriver");
                });

            modelBuilder.Entity("Fenio1.Core.Entities.RaceResult", b =>
                {
                    b.HasOne("Fenio1.Core.Entities.Driver", "Driver")
                        .WithMany("RaceResults")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fenio1.Core.Entities.Race", "Race")
                        .WithMany("RaceResults")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Fenio1.Core.Entities.SprintResult", b =>
                {
                    b.HasOne("Fenio1.Core.Entities.Driver", "Driver")
                        .WithMany("SprintResults")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fenio1.Core.Entities.Race", "Race")
                        .WithMany("SprintResults")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Fenio1.Core.Entities.Circuit", b =>
                {
                    b.Navigation("Races");
                });

            modelBuilder.Entity("Fenio1.Core.Entities.Driver", b =>
                {
                    b.Navigation("DriverStandings");

                    b.Navigation("QualifyingResults");

                    b.Navigation("RaceResults");

                    b.Navigation("SprintResults");
                });

            modelBuilder.Entity("Fenio1.Core.Entities.Prediction", b =>
                {
                    b.Navigation("QualifyingPositions");

                    b.Navigation("RacePositions");

                    b.Navigation("SprintPositions");
                });

            modelBuilder.Entity("Fenio1.Core.Entities.Race", b =>
                {
                    b.Navigation("Predictions");

                    b.Navigation("QualifyingResults");

                    b.Navigation("RaceExtras");

                    b.Navigation("RaceResults");

                    b.Navigation("SprintResults");
                });

            modelBuilder.Entity("Fenio1.Core.Entities.Season", b =>
                {
                    b.Navigation("ConstructorStandings");

                    b.Navigation("DriverStandings");

                    b.Navigation("Races");
                });

            modelBuilder.Entity("Fenio1.Core.Entities.Team", b =>
                {
                    b.Navigation("ConstructorStandings");

                    b.Navigation("Drivers");
                });

            modelBuilder.Entity("Fenio1.Core.Entities.User", b =>
                {
                    b.Navigation("Predictions");
                });
#pragma warning restore 612, 618
        }
    }
}
